

import '../06/heroes/prop/prop.dart';

List<String> get extraImages {
  List<String> result = [
    'break_bricks/Btn_V13.png',
    'break_bricks/Btn_V14.png',
    'break_bricks/Btn_V03.png',
    'break_bricks/Btn_V04.png',
    'break_bricks/Btn_V17.png',
    'break_bricks/Btn_V18.png',
    'break_bricks/Btn_V15.png',
    'break_bricks/Btn_V16.png',
    'break_bricks/Btn_V11.png',
    'break_bricks/Btn02.png',
    'break_bricks/Btn01.png',
    'break_bricks/BtnExitOpacity.png',
    'break_bricks/BtnExitNoOpacity.png',
    'break_bricks/blue_boxCheckmark.png',
    'break_bricks/grey_box.png',
    'break_bricks/red_cross.png',
    'break_bricks/buttonLong_beige.png',
    'break_bricks/buttonLong_beige_pressed.png',
    'break_bricks/shadedDark33.png',
    'break_bricks/shadedDark31.png',
    'break_bricks/shadedDark24.png',
    'break_bricks/texture_metal1.png',
    'break_bricks/texture_gem3.png',
    'break_bricks/texture_fabric1.png',
    'break_bricks/texture_ice1.png',
    'break_bricks/tile_0046.png',
    'break_bricks/tile_0044.png',
    'break_bricks/flatDark15.png',
    'break_bricks/flatDark13.png',
    'break_bricks/buttonLong_brown.png',
    'break_bricks/buttonLong_brown_pressed.png',
    'break_bricks/buttonLong_blue.png',
    'break_bricks/buttonLong_blue_pressed.png',
    'break_bricks/buttonLong_blue_pressed.png',
    'break_bricks/panel.png',
    'break_bricks/Window04.png',
    'break_bricks/level.png',
    'break_bricks/package.png',
    'break_bricks/Btn_V01.png',
    'break_bricks/Btn_V05.png',
    'break_bricks/prop_show_5s.png',
    'break_bricks/Cell01.png',
    'break_bricks/prop_random.png',
    'break_bricks/coin.png',
    'break_bricks/package_panel.png',
    'break_bricks/package_cell.png',
    'break_bricks/package_tab.png',
  ];
  result.addAll(Prop.values.map((e) => 'break_bricks/${e.src}'));
  return result;
}